version: '3'
services:

    backend:
        container_name: backend_container
        build: ./backend
        ports:
            - 9000:9000
        networks:
            - default

    frontend:
        container_name: frontend_container
        depends_on:
            - "backend"
        build: ./frontend
        ports:
            - 8080:8080
        networks:
            - default
        restart: always


networks:
  default:
