name: CD Production 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  Clone-down:
    runs-on: ubuntu-latest
    steps:
      - name: Clone-down
        uses: actions/checkout@v2   
      - name: Upload Code
        uses: actions/upload-artifact@v2
        with:
          name: code
          path: .
  Build-backend:
    runs-on: ubuntu-latest
    needs: Clone-down
    steps:
      - name: Download Code
        uses: actions/download-artifact@v2
        with: 
          name: code
          path: .
      - name: Setup Go
        uses: actions/setup-go@v3
      - name: Verify Go
        run: go mod verify
        working-directory: ./backend  
      - name: Build
        run: go build
        working-directory: ./backend
      - name: Upload Backend Binary
        uses: actions/upload-artifact@v2
        with:
          name: backend-bin
          path: ./backend/backend

  Build-frontend:
    runs-on: ubuntu-latest
    needs: Clone-down
    steps:
      - name: Download Code
        uses: actions/download-artifact@v2
        with: 
          name: code
          path: .
      - name: Setup Go
        uses: actions/setup-go@v3
      - name: Verify Go
        working-directory: ./frontend
        run: go mod verify          
      - name: Build
        working-directory: ./frontend
        run: go build
      - name: Upload Frontend Binary
        uses: actions/upload-artifact@v2
        with:
          name: frontend-bin
          path: ./frontend

  Test-frontend:
    runs-on: ubuntu-latest
    needs: Clone-down
    steps:
      - name: Download Repo
        uses: actions/download-artifact@v2
        with: 
          name: code
          path: .
      - name: Setup Go
        uses: actions/setup-go@v3
      - name: Verify Go
        working-directory: ./frontend
        run: go mod verify          
      - name: Test
        working-directory: ./frontend
        run: go test

  Docker-image-prod:
    runs-on: ubuntu-latest
    needs: [Build-backend, Build-frontend, Test-frontend]
    steps:
      - name: Download Repo
        uses: actions/download-artifact@v2
        with: 
          name: code
          path: .
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push backend
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/backend:prod
      - name: Build and push frontend
        uses: docker/build-push-action@v3
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/frontend:prod  

  Deploy-prod:
    runs-on: main-self-hosted
    needs: [Docker-image-prod]
    steps:
      - name: Nothing yet
        run: echo "Hello latest"         
