name: CD Staging
on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging
jobs:
  Clone-down:
    runs-on: ubuntu-latest
    steps:
      - name: Clone-down
        uses: actions/checkout@v2   
      - name: Upload Code
        uses: actions/upload-artifact@v2
        with:
          name: code
          path: .
  Build-backend:
    runs-on: ubuntu-latest
    needs: Clone-down
    steps:
      - name: Download Code
        uses: actions/download-artifact@v2
        with: 
          name: code
          path: .
      - name: Setup Go
        uses: actions/setup-go@v3
      - name: Verify Go
        run: go mod verify
        working-directory: ./backend  
      - name: Build
        run: go build
        working-directory: ./backend
      - name: Upload Backend Binary
        uses: actions/upload-artifact@v2
        with:
          name: backend-bin
          path: ./backend/backend

  Build-frontend:
    runs-on: ubuntu-latest
    needs: Clone-down
    steps:
      - name: Download Code
        uses: actions/download-artifact@v2
        with: 
          name: code
          path: .
      - name: Setup Go
        uses: actions/setup-go@v3
      - name: Verify Go
        working-directory: ./frontend
        run: go mod verify          
      - name: Build
        working-directory: ./frontend
        run: go build
      - name: Upload Frontend Binary
        uses: actions/upload-artifact@v2
        with:
          name: frontend-bin
          path: ./frontend

  Test-frontend:
    runs-on: ubuntu-latest
    needs: Clone-down
    steps:
      - name: Download Repo
        uses: actions/download-artifact@v2
        with: 
          name: code
          path: .
      - name: Setup Go
        uses: actions/setup-go@v3
      - name: Verify Go
        working-directory: ./frontend
        run: go mod verify          
      - name: Test
        working-directory: ./frontend
        run: go test

  Docker-image-staging:
    runs-on: ubuntu-latest
    needs: [Build-backend, Build-frontend, Test-frontend]
    steps:
      - name: Download Repo
        uses: actions/download-artifact@v2
        with: 
          name: code
          path: .
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push backend
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/backend:staging
      - name: Build and push frontend
        uses: docker/build-push-action@v3
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/frontend:staging  

  System-test-staging:
    runs-on: staging-self-hosted
    needs: [Docker-image-staging]
    steps:
      - name: Clone-down
        uses: actions/checkout@v2
      - name: Start docker-compose
        run: docker-compose up -d
      - name: Test
        run: docker run --network container:simple-fortune-cookie_frontend_1 appropriate/curl -s --retry 10 --retry-connrefused http://localhost:8080/  


  Deploy-staging:
    runs-on: staging-self-hosted
    needs: [System-test-staging]
    steps:
      - name: Nothing yet
        run: echo "Hello latest" 
